--- 
framework: jest
postMerge: 
  pattern: 
    - "**/*.test.js"
postRun: 
  command: 
    - "node --version"  
preMerge: 
  pattern: 
    - "**/*.test.js"
preRun: 
  command: 
    - npm ci    
version: 1.0.1
